<?php 
require_once('head.php');
require_once('header.php');
require_once('content.php');
require_once('footer.php');
require_once('modal.php');
require_once('js_global.php');
require_once('js.php');
?>